CustomerManagementSystem/Models/ErrorViewModel.cs
namespace CustomerManagementSystem.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CustomerManagementSystem/Models/MerchantCategory.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CustomerManagementSystem.Models
{
    public class MerchantCategory
    {
        [Key]
        public int Id { get; set; }
       
        [Required]
        [MaxLength(30)]
        [DisplayName("Category Name")]
        public string Name { get; set; }

        [DisplayName("Display Order")]
        [Range(1, 100, ErrorMessage ="Display order must be btween 1 - 100")]
        public int DisplayOrder { get; set; }
    }
}

CustomerManagementSystem/Controllers/HomeController.cs
using CMS.Models.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CustomerManagementSystem.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CustomerManagementSystem/Controllers/MerchantCategoryController.cs
using CMS.DataAccess.Data;
using CMS.Models.Models;
using Microsoft.AspNetCore.Mvc;

namespace CustomerManagementSystem.Controllers
{
    public class MerchantCategoryController : Controller
    {
        private ApplicationDbContext _db;

        public MerchantCategoryController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            List<MerchantCategory> objMerchantCategoryList = _db.MerchantCategories.ToList();

            return View(objMerchantCategoryList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(MerchantCategory obj)
        {
            
            if (ModelState.IsValid)
            { 
                _db.MerchantCategories.Add(obj);
                _db.SaveChanges();

                TempData["success"] = "Merchant category add successfully";

                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult Edit(int ? id)
        {
            if (id == null || id == 0)
                return NotFound();

            MerchantCategory? merchantCategory = _db.MerchantCategories.Find(id);

            if (merchantCategory == null)
                return NotFound();

            return View(merchantCategory);
        }

        [HttpPost]
        public IActionResult Edit(MerchantCategory obj)
        {

            if (ModelState.IsValid)
            {
                _db.MerchantCategories.Update(obj);
                _db.SaveChanges();

                TempData["success"] = "Merchant category Edited successfully";

                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult Susbend(int? id)
        {
            if (id == null || id == 0)
                return NotFound();

            MerchantCategory? merchantCategory = _db.MerchantCategories.Find(id);

            if (merchantCategory == null)
                return NotFound();

            return View(merchantCategory);
        }

        [HttpPost]
        public IActionResult Susbend(MerchantCategory obj)
        {
            if (obj == null)
                return NotFound();

            _db.MerchantCategories.Remove(obj);
            _db.SaveChanges();

            TempData["success"] = "Merchant category susbended successfully";

            return RedirectToAction("Index");
        }
    }
}

CustomerManagementSystem/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CustomerManagementSystem/Views/MerchantCategory/Create.cshtml
@model MerchantCategory

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Create Merchants Category</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post" class="row">
            <div class="border p-4">
                <div class="mb-3 row">
                    <label asp-for="Name" class="p-0"></label>
                    <input asp-for="Name" class="col-sm-3 border-top-0 border-end-0 border-start-0 border-1 bg-light-subtle form-control" style=" padding-left: 4px;" type="text" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="mb-3 row">
                    <label asp-for="DisplayOrder" class="p-0"></label>
                    <input asp-for="DisplayOrder" class="col-sm-3 border-top-0 border-end-0 border-start-0 border-1 bg-light-subtle form-control" style="padding-left: 4px;" type="text" />
                    <span asp-validation-for="DisplayOrder" class="text-danger"></span>

                </div>

                <div class="row">
                    <div class="col-6">
                        <button type="submit" class="btn btn-primary form-control">Create Category</button>
                    </div>
                    <div class="col-6">
                        <a asp-controller="MerchantCategory" asp-action="index" class="btn btn-outline-secondary border form-control">Back</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>



@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

CustomerManagementSystem/Views/MerchantCategory/Edit.cshtml
@model MerchantCategory

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Edit Merchants Category</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post">
            <input asp-for="Id" hidden />

            <div class="border p-4">
                <div class="mb-3 row">
                    <label asp-for="Name" class="p-0"></label>
                    <input asp-for="Name" class="col-sm-3 border-top-0 border-end-0 border-start-0 border-1 bg-light-subtle form-control" style=" padding-left: 4px;" type="text" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="mb-3 row">
                    <label asp-for="DisplayOrder" class="p-0"></label>
                    <input asp-for="DisplayOrder" class="col-sm-3 border-top-0 border-end-0 border-start-0 border-1 bg-light-subtle form-control" style="padding-left: 4px;" type="text" />
                    <span asp-validation-for="DisplayOrder" class="text-danger"></span>

                </div>

                <div class="row">
                    <div class="col-6">
                        <button type="submit" class="btn btn-primary form-control">Update</button>
                    </div>
                    <div class="col-6">
                        <a asp-controller="MerchantCategory" asp-action="index" class="btn btn-outline-secondary border form-control">Back</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>




@section Scripts
    {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    }

CustomerManagementSystem/Views/MerchantCategory/Index.cshtml
@model List<MerchantCategory>

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Merchant Category</h2>
            </div>
        </div>
    </div>

    <div class="card-body p-4">
        <div class="pb-1 text-end">
            <a asp-controller="MerchantCategory" asp-action="Create" class="btn btn-primary" title="">
                <i class="bi bi-plus-circle"></i> Create new category
            </a>
        </div>
        <div class="border p-4">
            <table class="table table-border table-striped">

                <thead>
                    <tr>
                        <th class="text-center">
                            Category Name
                        </th>
                        <th class="text-center">
                            Display Order
                        </th>
                        <th class="text-center">
                            Actions
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var obj in Model.OrderBy(u => u.DisplayOrder))
                    {
                        <tr>
                            <td style="vertical-align: middle;" class="ps-3">
                                @obj.Name
                            </td>
                            <td style="vertical-align: middle; text-align: center;">
                                @obj.DisplayOrder
                            </td>
                            <td class="d-flex justify-content-center btn-group" role="group">
                                <a asp-controller="MerchantCategory" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-warning">
                                    <i class="bi bi-pencil-square"></i> Edit
                                </a>
                                <a asp-controller="MerchantCategory" asp-action="Susbend" asp-route-id="@obj.Id" class="btn btn-danger">
                                    <i class="bi bi-trash3"></i> Susbend
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

CustomerManagementSystem/Views/MerchantCategory/Susbend.cshtml
@model MerchantCategory

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Susbend Merchants Category</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post">
            <input asp-for="Id" hidden />
            <div class="border p-4">
                <div class="row pb-2">
                    <h2>Susbend Merchants Category</h2>
                    <hr />
                </div>
                <div class="mb-3 row">
                    <label asp-for="Name" class="p-0"></label>
                    <input asp-for="Name" disabled class="col-sm-3 border-top-0 border-end-0 border-start-0 border-1 bg-light-subtle form-control" style=" padding-left: 4px;" type="text" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="mb-3 row">
                    <label asp-for="DisplayOrder" class="p-0"></label>
                    <input asp-for="DisplayOrder" disabled class="col-sm-3 border-top-0 border-end-0 border-start-0 border-1 bg-light-subtle form-control" style="padding-left: 4px;" type="text" />
                </div>
                <div class="row">
                    <div class="col-6">
                        <button type="submit" class="btn btn-danger form-control">Susbend</button>
                    </div>
                    <div class="col-6">
                        <a asp-controller="MerchantCategory" asp-action="index" class="btn btn-outline-secondary border form-control">Back</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

CustomerManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CustomerManagementSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/CustomerManagementSystem.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"/>

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CMS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li>
                            <a class="nav-link" asp-controller="MerchantCategory" asp-action="Index">Merchant Category</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top bg-primary footer text-white">
        <div class="text-center">
            &copy; 2023 - CustomerManagementSystem <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CustomerManagementSystem/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib//jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">toastr.success('@TempData["success"]');</script>
}

@if(TempData["error"] != null)
{
    <script src="~/lib//jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
        <script type="text/javascript">toastr.error('@TempData["error"]');</script>
}